### PR TITLE
Solution: Storage Adapter

### PR DESCRIPTION
**Pull request by maennchen**
~~Based on #317, merge that PR first.~~

Partial Implementation of #240

This PR is currently only to track changes, do not merge until it is proven to be working with an actual storage implementation.

### CODE REVIEW

**Comment by maennchen** [comment]
@c-rack Do you have any idea how to capture logs in a tests `setup` block?

**Comment by c-rack** [comment]
@maennchen no idea, sorry

**Comment by maennchen** [comment]
@c-rack I'm going to ask around then.

**Comment by barthez** [comment]
@maennchen Hi! Have you tried `capture_log` from `ExUnit.CaptureLog` module. I have tried it and works in `setup` block as well.

**Comment by maennchen** [comment]
@barthez I tried using it, but I need the created values and capture_log returns the logs and not those values. (I need to pass them to the return of the setup.)

Do you know a way around that?

**Comment by barthez** [comment]
I don't know another way around it than sending a message to self:
```elixir
      capture_log(fn ->
        {:ok, broadcaster} =
          start_supervised(
            {ExecutionBroadcaster, {__MODULE__, producer, TestStorage, TestScheduler}}
          )

        send(self(), {:boardcaster, broadcaster})
      end)

      broadcaster =
        receive do
          {:boardcaster, result} -> result
        end
```

**Comment by maennchen** [comment]
I haven’t thought of that. I don’t really like the solution, but it is way better than a jamed test log. I’ll change that.

**Comment by barthez** [comment]
Looks nice. Maybe `ExUnit` deserves a PR? I doubt you are the only one struggling with this problem.

**Comment by maennchen** [comment]
> Maybe ExUnit deserves a PR?

We'd have to write a proposal to the Mailing List. Creating PR's directly is not always appreciated.

**Comment by c-rack** [comment]
@maennchen Sure, I agree. I have created https://github.com/quantum-elixir orga and invited you as owner. It is great to see this project evolving. We should be open to everyone to contribute to this project under the C4 process and invite contributors to join the team. Feel free to migrate this project to the new orga as you like.

**Comment by maennchen** [comment]
Cool! Thank you. I‘ll figure out the details of the migration tomorrow.

**Comment by c-rack** [comment]
Ok. We should agree a naming schema for the repos in that orga. Maybe `quantum-core` for the base library and `quantum-storage-xxx` for the xxx-storage adapters. What do you think?

**Comment by maennchen** [comment]
I agree. Do I have owner rights on that repo so that I can move it? (I know that I have them in the orga, but here I don‘t know.)

I‘ll transfer the image to the orga, rename to quantum-core. After that we should fork it back here so that the url still works.

After that we should create a new release pointing to the new urls. In the forked back repo here we should update the readme with a notice that the repo has been moved.

After all that is done, I‘ll extract the storage adapter into its own repo.

**Comment by c-rack** [comment]
@maennchen just looked and found no option to give you owner permissions on this repo, but I can do the transfer. One thing regarding the naming: if we rename the project and fork back, the URLs will still break. So maybe it is better to keep the project name as it is, ok?

**Comment by maennchen** [comment]
@c-rack You can always rename a repository.

I would do it like this:

* Transfer repo to orga
* Rename orga repo to quantum-core
* Fork orga repo to your local account
* Rename personal fork back to quantum-elixir

When you're done I'll go and change the links in the `mix.exs` and `README.md` swiftly to the new location.

This way we should break no urls and have everything named correctly.

**Comment by c-rack** [comment]
@maennchen transfer completed, fork is already renamed and I've added you as collaborator for the README changes.

**Comment by maennchen** [comment]
@pyatkov I removed your changes and put them into this repo: https://github.com/quantum-elixir/quantum-storage-ets

I will stabilize the code and add tests. After that we should be able to release the new API and the ets storage package.

**Comment by maennchen** [comment]
@c-rack Would it be ok to mark this module as "experimental" and not adhere to the semantic versioning as we do with the rest of the library. (Only until it is stabilized)

**Comment by maennchen** [comment]
@c-rack Great! Then I'm ready to release it into the wild I think.

**Comment by maennchen** [comment]
PS: I'm adding documentation as soon as it is stable.

**Comment by c-rack** [comment]
Great :)

**Pull request merged**
