### PR TITLE
feat: Registers telemetry events

### LINKED ISSUE #492: Documenting `telemetry` events with `telemetry_registry`
### Discussed in https://github.com/quantum-elixir/quantum-core/discussions/491

<div type='discussions-op-text'>

<sup>Originally posted by **isaacsanders** November 12, 2021</sup>
This would enable integration with tools like https://github.com/opentelemetry-beam/opentelemetry_telemetry

I'm also happy to do the work.</div>

### PR DESCRIPTION
**Pull request by isaacsanders**
Fixes #492 

```
iex(1)> :telemetry_registry.discover_all(:quantum)
:ok
iex(2)> :telemetry_registry.spannable_events()
[{[:quantum, :job], [:start, :stop, :exception]}]
iex(3)> :telemetry_registry.list_events
[
  {[:quantum, :job, :add], Quantum.JobBroadcaster,
   %{
     description: "dispatched when a job is added",
     measurements: "%{}",
     metadata: "%{job: Quantum.Job.t(), scheduler: atom()}"
   }},
  {[:quantum, :job, :delete], Quantum.JobBroadcaster,
   %{
     description: "dispatched when a job is deleted",
     measurements: "%{}",
     metadata: "%{job: Quantum.Job.t(), scheduler: atom()}"
   }},
  {[:quantum, :job, :exception], Quantum.Executor,
   %{
     description: "dispatched on job execution fail",
     measurements: "%{duration: integer()}",
     metadata: "%{telemetry_span_context: term(), job: Quantum.Job.t(), node: Node.t(), scheduler: atom(), kind: :throw | :error | :exit, reason: term(), stacktrace: list()}"
   }},
  {[:quantum, :job, :start], Quantum.Executor,
   %{
     description: "dispatched on job execution start",
     measurements: "%{system_time: integer()}",
     metadata: "%{telemetry_span_context: term(), job: Quantum.Job.t(), node: Node.t(), scheduler: atom()}"
   }},
  {[:quantum, :job, :stop], Quantum.Executor,
   %{
     description: "dispatched on job execution end",
     measurements: "%{duration: integer()}",
     metadata: "%{telemetry_span_context: term(), job: Quantum.Job.t(), node: Node.t(), scheduler: atom(), result: term()}"
   }},
  {[:quantum, :job, :update], Quantum.JobBroadcaster,
   %{
     description: "dispatched when a job is updated",
     measurements: "%{}",
     metadata: "%{job: Quantum.Job.t(), scheduler: atom()}"
   }}
]
```

### CODE REVIEW

**Comment by maennchen** [comment]
@isaacsanders Thanks!

I was wondering, if it would be better to move the events into a module that has a `@moduledoc`  and include `telemetry_docs()`  in there. What do you think?

Should we add something similar to your example above to the tests?

**Comment by isaacsanders** [comment]
how do you like this newest set of changes?

**Comment by maennchen** [comment]
@isaacsanders Do you think that we should have a separate module for the Telemetry Docs? I think it would also be fine to add it directly to the `Quantum` module itself. What do you think?

**Review by maennchen — APPROVED** [review]

**Comment by maennchen** [comment]
@isaacsanders Awesome, thank you 🙂

**Pull request merged**
