### PR TITLE
Solution: solve job broadcaster process can not found in global mode

### PR DESCRIPTION
**Pull request by redink**
## Scenario
I using global mode to set the job and in multi-nodes env, and I'd like to get the `jobs`.

## Problem
But if I get the jobs on one Elixir node which doesn't keep the global `MyApp.Scheduler.TaskStagesSupervisor` process, the error will happen:

```
1> MyApp.Scheduler.jobs
** (exit) exited in: GenServer.call(MyApp.Scheduler.JobBroadcaster, :jobs, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:821: GenServer.call/3
```

## Surmise
I scanned the code, and found,

1, the job broadcaster from here https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/scheduler.ex#L66
2, the job broadcaster defined here https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum.ex#L39

That is, the job broadcaster always one local process rather than global one. So, if `node a` keep the  global `MyApp.Scheduler.TaskStagesSupervisor`  process, and `node b` invoke relevant interfaces, the above error will happen.

## Solution
Use `{process_name, process_node}` as job broadcaster if the application use global mode and the node doesn't keep the global `MyApp.Scheduler.TaskStagesSupervisor` process.

## Need help
I tested fix-branch in my own project, it works well.

But, I don't know how to write test case to cover this scenario. I did not find any test case to cover global mode from base code.

### CODE REVIEW

**Comment by maennchen** [comment]
Thank you for your PR!

I‘m thinking if there is a better way to achieve the result. Would it be a better idea to call those methods via the TaskStagesSupervisor which will aöways have the reference to the global JobSupervisor?

This way we would not need as many changes.

What do you think?

**Comment by c-rack** [comment]
@redink thanks for the PR! It will be megred shortly.

@maennchen according to our C4 process, this PR solves a problem and passes the tests. Even if there is a better solution, please do not hesitate to merge such requests. It is part of the C4 process to merge quickly and discuss/revert/improve afterwards. I understand that this _might_ sound strange, but it is a very powerful and successful method :)

**Comment by maennchen** [comment]
@c-rack Can you explain me how releasing works with C4? When exactly do we release and when would we wait until we „like“ the implementation?

**Comment by maennchen** [comment]
Also according to C4: I have not yet merged the storage PR because I first want to stabilize the Behaviour. If I released it, we could get problems with changes because implementation might break. How de we handle that according to C4?

**Comment by redink** [comment]
@c-rack Thanks.

@maennchen But `TaskStagesSupervisor` is one supervisor process, it is not good if we invoke these interfaces via one supervisor. Supervisor process should not introduce too many business logic.

Our goal is find the process which in charge of broadcast job, but this process is not in all node rather than one of the cluster in global mode. So I think there are two ways to achieve:

- use form of `{process_name, process_node}` (that is I using in this pr)
- set the job broadcaster process to global

However, I think "via TaskStagesSupervisor" same as "set the job broadcaster process to global", they are both need one global process essentially.

**Comment by c-rack** [comment]
Regarding C4 process, there is a more detailed description from its originator here:
https://hintjens.gitbooks.io/social-architecture/content/chapter4.html

The important part is in section "Development Process", where the difference between optimistic and pessimistic merging is explained. Once one gets used to optimistic merging, it works like a charm (higher code quality, active contributors, happy users, etc).

Regarding releases, the C4 process is not that clear. In ZeroMQ, we make releases if there is demand from the community to do so or if a maintainer decides to make a new release. To avoid breaking changes, there is the model of "Evolution of Public Contracts" in C4. It may not be transferrable one to one to this project, but as long as improvements and bugfixes do not change the public API of Quantum (which I don't see in this PR) and pass the tests, everything is going fine. We can have a Skype call about C4 and releases to discuss this further if you like.

**Comment by maennchen** [comment]
@c-rack I‘d really like a quick call some time to really understand how you want to work here.

**Comment by redink** [comment]
New release please? Thanks in advance.

**Comment by maennchen** [comment]
@redink I‘d like to fix the issue #334 before releasing. Without that the global mode still does not work reliably.

**Pull request merged**
