### PR TITLE
Implement date library using elixir 1.8s core functionality

### PR DESCRIPTION
**Pull request by LostKobrakai**
As the title says. I'm just not sure what would be the best way to put tzdata into the deps, as really it's probably not even an optional dependency. It would just need to be available for :dev and :test.

### CODE REVIEW

**Comment by maennchen** [comment]
@LostKobrakai Thanks a lot for your PR. If you don't mind I would keep this PR open until `tzdata` is stable and then immediately merge & create a new release.

Why would it only need to be available for `dev` and `test`? This should work just as well in `prod`.

**Comment by LostKobrakai** [comment]
By now tzdata is the only actual implementation for a timezone database, but the code I added would work with any implementation, so there's no need for quantum to require any tzdata version. It would rather just happen to be the implementation used in dev/test.

**Comment by njwest** [comment]
Looks like `tzdata` has moved from rc to [official 1.0.0 release](https://github.com/lau/tzdata) as of April 24

**Comment by LostKobrakai** [comment]
This is still blocked because timex does not yet allow for tzdata 1.0: https://github.com/bitwalker/timex/issues/530

**Comment by maennchen** [comment]
I'll try to work towards version 3. Since elixir offers all capabilities by itself, `timex` and `calendar` will no longer be needed. Therefore I'm going to merge this PR and remove all time libraries instead.

**Pull request merged**
